/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_dreeks_audhumla_jni_JNIVibrancyWindows */

#ifndef _Included_xyz_dreeks_audhumla_jni_JNIVibrancyWindows
#define _Included_xyz_dreeks_audhumla_jni_JNIVibrancyWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_dreeks_audhumla_jni_JNIVibrancyWindows
 * Method:    SetWindowAcrylic
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xyz_dreeks_audhumla_jni_JNIVibrancyWindows_SetWindowAcrylic
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
